//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasificacionRestaurante
    {
        public int ID_ClasificacionRestaurante { get; set; }
        public Nullable<int> Clasificacion { get; set; }
        public Nullable<int> ID_Restaurante { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
    }
}
