//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int ID_Direccion { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string CodigoPostal { get; set; }
        public string DireccionExacta { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
