//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaDetalle
    {
        public int ID_LineaDetalle { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<int> ID_OrdenCompra { get; set; }
    
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
