//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int ID_Pago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<int> ID_TipoMoneda { get; set; }
        public Nullable<int> ID_OrdenCompra { get; set; }
    
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
    }
}
