//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.LineaDetalle = new HashSet<LineaDetalle>();
        }
    
        public int ID_Producto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Precio { get; set; }
        public string TiempoPreparacion { get; set; }
        public Nullable<int> Impuesto { get; set; }
        public byte[] Fotografia { get; set; }
        public string EstadoActual { get; set; }
        public Nullable<int> ID_TipoProducto { get; set; }
        public Nullable<int> ID_Restaurante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaDetalle> LineaDetalle { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
