//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int ID_Tarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string MesVencimiento { get; set; }
        public string AnnoVencimiento { get; set; }
        public string CodigoSeguridad { get; set; }
        public string EstadoActual { get; set; }
        public Nullable<int> ID_TipoTarjeta { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
    
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
